---
- name: AdGuard Home requirements
  hosts: homelab
  become: true

  tasks:
    - name: Stop systemd-resolved service
      systemd:
        name: systemd-resolved
        state: stopped

    - name: Disable systemd-resolved service
      systemd:
        name: systemd-resolved
        enabled: false

    - name: Remove /etc/resolv.conf symlink
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Create new /etc/resolv.conf
      copy:
        content: |
          nameserver 1.1.1.1
          nameserver 1.0.0.1
        dest: /etc/resolv.conf
        mode: '0644'
