---
- name: Schedule backup
  hosts: homelab
  become: true

  vars:
    backup_directories:
      - source: "/docker/data/"
        dest: "/mnt/nas/docker_data/"
      - source: "/docker/paperless/"
        dest: "/mnt/nas/paperless/"
      - source: "/docker/syncthing/"
        dest: "/mnt/nas/syncthing/"
      - source: "/docker/books/"
        dest: "/mnt/nas/books/"
    healthchecks_backup_url: "{{ lookup('env', 'HEALTHCHECKS_BACKUP_URL') }}"
    healthchecks_backup_secrets_url: "{{ lookup('env', 'HEALTHCHECKS_BACKUP_SECRETS_URL') }}"
    backup_jobs:
      - name: "backup"
        description: "regular files using rsync"
        template_file: "backup.sh.j2"
        schedule: "01:00:00"
        log_path: "/var/log/backup.log"
        healthcheck_url: "{{ lookup('env', 'HEALTHCHECKS_BACKUP_URL') }}"
      - name: "backup-secrets"
        description: "application secrets (.env files) using gpg"
        template_file: "backup-secrets.sh.j2"
        schedule: "00:55:00"
        log_path: "/var/log/backup-secrets.log"
        healthcheck_url: "{{ lookup('env', 'HEALTHCHECKS_BACKUP_SECRETS_URL') }}"

  tasks:
    - name: Ensure backup script directory exists
      file:
        path: /usr/local/bin
        state: directory
        mode: '0755'

    - name: Create the backup scripts from templates
      template:
        src: "templates/{{ item.template_file }}"
        dest: "/usr/local/bin/{{ item.name }}"
        mode: '0755'
      loop: "{{ backup_jobs }}"

    - name: Create systemd services
      copy:
        dest: "/etc/systemd/system/{{ item.name }}.service"
        content: |
          [Unit]
          Description=Run backup script for {{ item.description }}

          [Service]
          Type=oneshot
          ExecStart=/usr/local/bin/{{ item.name }}

          [Install]
          WantedBy=multi-user.target
      loop: "{{ backup_jobs }}"
      notify: Reload systemd

    - name: Create systemd timers
      copy:
        dest: "/etc/systemd/system/{{ item.name }}.timer"
        content: |
          [Unit]
          Description=Run {{ item.name }} script on a schedule
          [Timer]

          OnCalendar=*-*-* {{ item.schedule }}
          Persistent=true

          [Install]
          WantedBy=timers.target
      loop: "{{ backup_jobs }}"
      notify: Reload systemd

    - name: Enable and start the systemd timers
      systemd:
        name: "{{ item.name }}.timer"
        enabled: true
        state: started
      loop: "{{ backup_jobs }}"

    - name: Configure logrotate for backup logs
      copy:
        dest: "/etc/logrotate.d/{{ item.name }}"
        content: |
          su root root
          {{ item.log_path }} {
              weekly
              rotate 4
              compress
              missingok
              notifempty
              create 0640 root root
              sharedscripts
              postrotate
                  systemctl reload rsyslog > /dev/null 2> /dev/null || true
              endscript
          }
      loop: "{{ backup_jobs }}"

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: true
