---
- name: Homelab configuration
  hosts: homelab

  tasks:
    - name: Generate SSH keys
      openssh_keypair:
        path: ~/.ssh/id_ed25519
        type: ed25519
    - name: Clone git repository
      git:
        repo: git@gitlab.com:Madh93/homelab.git
        dest: ~/Workspace/repos/homelab
        version: master
        accept_hostkey: yes
