---
- name: Main configuration
  hosts: homelab
  become: true

  tasks:
    - name: Install essential packages
      apt:
        name:
          - git
          - ca-certificates
          - curl
          - lm-sensors
          - htop
          - wakeonlan
          - fzf
          - gron
          - vim
          - logrotate
          - p7zip           # 7z
          - apache2-utils   # htpasswd
          - net-tools       # netstat

- name: Configure Homelab
  import_playbook: homelab.yml

- name: Configure Docker
  import_playbook: docker.yml

- name: Configure AdGuard Home
  import_playbook: adguard_home.yml

- name: Configure NFS Mounts
  import_playbook: mount.yml

- name: Configure Backup
  import_playbook: backup.yml
