---
- name: Configure NFS mounts
  hosts: homelab
  become: true

  vars:
    mount_directories:
      - name: docker_data
        path: 192.168.1.6:/volume1/docker_data
      - name: paperless
        path: 192.168.1.6:/volume1/paperless
      - name: syncthing
        path: 192.168.1.6:/volume1/syncthing
      - name: books
        path: 192.168.1.6:/volume1/books
      - name: comics
        path: 192.168.1.6:/volume1/comics
      - name: downloads
        path: 192.168.1.6:/volume1/downloads
      - name: photos
        path: 192.168.1.6:/volume1/photos
      - name: media
        path: 192.168.1.6:/volume1/media

  tasks:
    - name: Install required dependencies
      apt:
        pkg:
          - nfs-common

    - name: Create NAS mount directory
      file:
        path: /mnt/nas
        state: directory
        mode: '0755'

    - name: Create systemd mount files for NFS shares
      copy:
        dest: "/etc/systemd/system/mnt-nas-{{ item.name }}.mount"
        content: |
          [Unit]
          Description=Mount NAS {{ item.name }}

          [Mount]
          What={{ item.path }}
          Where=/mnt/nas/{{ item.name }}
          Type=nfs
          Options=vers=4
          TimeoutSec=30

          [Install]
          WantedBy=multi-user.target
      loop: "{{ mount_directories }}"
      notify:
        - Reload systemd

    - name: Enable and start the systemd mounts
      systemd:
        name: "mnt-nas-{{ item.name }}.mount"
        enabled: true
        state: started
      loop: "{{ mount_directories }}"

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
